services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: admin
    restart: unless-stopped
    ports:
      - "8888:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - selenoid_network

  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - selenoid_network

  prestashop:
    image: prestashop/prestashop:9-apache
    container_name: prestashop
    restart: always
    ports:
      - "8081:80"
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWORD: admin
      DB_PREFIX: ps_
      PS_INSTALL_AUTO: "1"
      PS_LANGUAGE: en
      PS_COUNTRY: US
      ADMIN_MAIL: admin@example.com
      ADMIN_PASSWD: Admin123!
      PS_FOLDER_ADMIN: administration
      PS_DOMAIN: prestashop
    volumes:
      - ps_data:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - selenoid_network
    healthcheck: #ДОБАВИЛ ВОТ ЭТО
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  prestashop_postinstall:
    image: alpine:3.19
    depends_on:
      - prestashop
    volumes:
      - ps_data:/var/www/html
    restart: "no"
    command: >
      sh -lc '
        apk add --no-cache curl >/dev/null 2>&1 || true;
        until curl -fsS http://prestashop/ >/dev/null; do sleep 5; done;
        until [ -f /var/www/html/config/settings.inc.php ] || [ -f /var/www/html/app/config/parameters.php ]; do sleep 2; done;
        sleep 10;
        rm -rf /var/www/html/install /var/www/html/install-dev;
        rm -rf /var/www/html/var/cache/* || true;
      '
    networks:
      - selenoid_network

  selenoid:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid/config/browsers.json:/etc/selenoid/browsers.json:ro
    command:
      - "-conf"
      - "/etc/selenoid/browsers.json"
      - "-container-network"
      - "selenoid_network"
      - "-timeout"
      - "5m"
    depends_on:
      - prestashop
    networks:
      - selenoid_network

  selenoid_ui:
    image: aerokube/selenoid-ui:1.10.11
    container_name: selenoid_ui
    ports:
      - "8082:8080"
    command:
      - "--selenoid-uri"
      - "http://selenoid:4444"
    depends_on:
      - selenoid
    networks:
      - selenoid_network

volumes:
  db_data:
  ps_data:

networks:
  selenoid_network:
    name: selenoid_network
    driver: bridge