[pytest]
addopts = -v -s --alluredir=allure-results --clean-alluredir
markers =
    main_page: mark as main page
    clothes_page: mark as clothes_page
    product_card: mark as product_card
    registration_page: mark as registration page
    administration_page: mark as administration page