[pytest]
addopts = -v -s
markers =
    json: mark as json placeholder service
    json_user: mark as json user handler
    json_post: mark as json post handler
    brewery: mark as brewery handler
    dog: mark as dog handler